### ISSUE TITLE
ContentClient not being able to deploy entities due to Uint8Array form-data append error

### ISSUE THREAD

**Issue by guidota** [decentraland/catalyst-client#151]
This line is causing an error when deployment data includes files with an Uint8Array instance.

https://github.com/decentraland/catalyst-client/blob/master/src/ContentClient.ts#L117

With recently changes the entity json content file is being generated using a Uint8Array instance and producing a runtime error:
`TypeError: source.on is not a function`

There is a reported issue in `form-data` repository: https://github.com/form-data/form-data/issues/220

To easily reproduce the issue you can run this script:
```javascript
const FormData = require("form-data");

const uintArray = new Uint8Array(10);

const formData = new FormData();
formData.append("file", uintArray);

==============================
❯ node index.js
../test/node_modules/delayed-stream/lib/delayed_stream.js:33
  source.on('error', function() {});
         ^

TypeError: source.on is not a function
    at Function.DelayedStream.create (../test/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (../test/node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (../test/node_modules/form-data/lib/form_data.js:75:3)
    at Object.<anonymous> (../test/index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by guidota** [comment]
This can be fixed by copying the array to a buffer by doing something like: `Buffer.from(uintArray)` but is kind of reverting to Buffer implementation.

@menduz

**Comment by menduz** [comment]
https://github.com/decentraland/catalyst-client/pull/153
